                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
  #academia         : # URL
  #arxiv            : # URL - Update with the correct link to your profile
  #googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  #inspire-hep      : # URL
  #impactstory      : # URL
  #orcid            : "https://orcid.org/yourorcidurl"
  #semantic         : # URL
  #ssrn             : # URL
  #pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  #researchgate     : # URL
  #scopus           : # URL
  #zotero           : # URL
















  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  #github           : "academicpages"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    








  # Social media
  artstation       : # Username
  #bluesky          : "bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
